image: node:16
pipelines:
  branches:
    develop:
      - step:
          name: 'Prepare build'
          deployment: staging
          script:
            - apt-get update && apt-get install gettext-base
            - mkdir tmp
            - mkdir tmp/server && mkdir tmp/client
            - cd server
            - yarn
            - cd config
            - cat production.config.ci | envsubst > production.json
            - cd ../
            - yarn build
            - cp -R dist/ node_modules/ config/ package.json ../tmp/server
            - cd ../client
            - cat config.json.prod.example | envsubst > config.json
            - yarn
            - yarn build
            - cp -R node_modules/ config.json dist/
            - cp -R dist/ ../tmp/client
            - cd ../ && tar -czvf crucible.tar.gz tmp/
          artifacts:
            - crucible.tar.gz
      - step:
          name: 'Deploy to zone'
          script:
            # Install the triton and manta tools
            - npm install -g git+https://github.com/eait-itig/node-triton#eait
            - npm install -g manta

            # Set up our profile
            - triton profile create -f .triton.json
            - eval "$(triton env uqcloud)"
            - export MANTA_URL=https://stluc.manta.uqcloud.net

            # Start an SSH agent with the bitbucket SSH key in it, we will use this for auth
            - export KEYPATH=$(cat ~/.ssh/config | grep '^IdentityFile' | awk '{print $2}')
            - eval $(ssh-agent)
            - ssh-add ${KEYPATH}

            # Now upload the tarball
            - mput -f crucible.tar.gz /elipse/stor/builds/deploy-${BITBUCKET_BUILD_NUMBER}.tar.gz --account=elipse --subuser=piper --role-tag=bitbucket-pipe
            - export TARBALL="$(msign /elipse/stor/builds/deploy-${BITBUCKET_BUILD_NUMBER}.tar.gz)"

            #   # And the actual deploy steps on each zone
            - triton --act-as=elipse inst exec $ZONE_NAME -- /bin/sh -c "cd /opt/ && rm -rf tmp && mkdir tmp/ &&
              curl \"${TARBALL}\" | tar -C tmp/ -zxvf - &&
              rm -rf /opt/server && cp -R /opt/tmp/tmp/server /opt && rm -rf /var/www/client && cp -R /opt/tmp/tmp/client /var/www/ &&
              systemctl restart crucible"
